version: "3.9"

services:
  java-1:
    container_name: infra-java-1
    image: infra-java-1
    restart: unless-stopped
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.local
      context: ../../Spring Boot Java/docker
    ports:
      - "${API_EXPOSED_PORT:-10081}:8080"
    environment:
      VIRTUAL_HOST: "${API_VIRTUAL_HOST:-api.paperless.local}"
    working_dir: /opt/app
    volumes:
      - ../../api:/opt/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.m2:/root/.m2
    command: bash -c "chmod +x scripts/run_local.sh && ./scripts/run_local.sh"
    networks:
      - infra-local-network

networks:
  infra-local-network:
    name: ${EXTERNAL_NETWORK:-infra-local-network}
    external: true